# 가설 1

## 라이브러리 임포트

In [7]:
from glob import glob
import pandas as pd

## 데이터 불러오기

In [8]:
files = sorted(glob('../../../data/likelion-ai-s7-mid/01*/local*.csv'))
files

['../../../data/likelion-ai-s7-mid\\01_seoul-living-popluation\\LOCAL_PEOPLE_GU_2019.csv',
 '../../../data/likelion-ai-s7-mid\\01_seoul-living-popluation\\LOCAL_PEOPLE_GU_2020.csv',
 '../../../data/likelion-ai-s7-mid\\01_seoul-living-popluation\\LOCAL_PEOPLE_GU_2021.csv']

In [9]:
data = pd.read_csv(files[0], encoding='cp949')
data

,기준일ID,시간대구분,자치구코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
20190101,0,11110,247783.9476,6613.1044,3564.9470,6134.7190,12757.6730,13424.9912,9679.4043,9262.2696,...,8455.5240,8669.4651,7764.7926,9659.7779,8421.0455,8671.2045,8079.0106,6242.6970,17962.9680,2.019011e+13
20190101,0,11140,176516.2769,4735.9065,1857.9963,3251.4707,7456.5552,8482.9745,8253.8513,8825.0475,...,7425.3943,7345.0904,5858.8981,6255.6065,5525.2377,6293.4810,5906.2118,4298.7062,12303.3213,2.019011e+13
20190101,0,11170,287806.8492,7274.7405,3654.3768,5865.4531,11656.1407,15548.7770,14457.9881,14558.2617,...,13423.3780,13009.2350,10794.0704,10880.1619,8360.3558,9568.1641,8703.7465,6648.3724,20296.2431,2.019011e+13
20190101,0,11200,335106.5204,12278.8839,5306.1528,6766.7787,11593.4668,13941.8426,13447.0673,15633.1375,...,14046.9836,15142.1260,12029.9710,13051.1879,11475.2065,13219.4730,12022.8741,9093.4057,24370.0786,2.019011e+13
20190101,0,11215,399818.0269,12003.9916,6472.3827,12056.0837,17503.8179,18611.2942,16219.1953,16342.7514,...,16189.7277,16158.7700,14059.8023,15750.9307,14705.5715,15708.3156,14021.6731,9907.6266,24975.8391,2.019011e+13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20191231,23,11620,512045.7410,13292.1313,6492.1774,10001.0660,20423.9464,34108.8311,27984.1499,24230.3331,...,22645.1803,20459.1792,16839.3671,17200.5078,16012.9977,18377.4578,16540.6608,13771.6139,32595.2666,2.020011e+13
20191231,23,11650,507017.9562,17249.4614,9728.3280,15440.6841,15643.9679,18565.4597,17723.9030,21873.1745,...,18778.2261,23145.8814,21481.7859,22961.2336,17494.8242,17660.0288,16583.0255,12881.3183,30976.3635,2.020011e+13
20191231,23,11680,701730.1925,21768.6379,14313.7773,22627.7125,21085.1486,29039.6792,28890.8864,32848.9924,...,29317.5029,32070.2938,30395.5776,31006.2854,21940.4235,22145.4239,21115.0631,16258.7322,39325.7057,2.020011e+13
20191231,23,11710,776809.6518,29303.9813,15154.6352,21907.8004,21864.3757,29286.5636,29977.2304,35285.9001,...,32816.1799,35769.2569,30872.0662,31988.1565,27188.8780,31098.6350,27865.7032,20081.3478,44078.4656,2.020011e+13
20191231,23,11740,522271.9542,20543.7319,10960.7816,14363.6445,13441.0008,16460.9813,17401.2642,21693.0864,...,18320.0779,22014.1676,20677.4726,21839.8532,19902.3094,23881.2715,21770.4235,16505.9461,35222.8552,2.020011e+13